# Generated by Django 5.0.4 on 2024-05-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='imgbb_url',
            field=models.URLField(blank=True),
        ),
    ]
